parameters:
    app.email.address: '%env(resolve:APP_EMAIL_ADDRESS)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Exception\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
